
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FormatServiceService", targetNamespace = "http://format/", wsdlLocation = "file:/users/alumnos-16-17/a0363813/Documentos/distribuidos/format/FormatService.wsdl")
public class FormatServiceService
    extends Service
{

    private final static URL FORMATSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FORMATSERVICESERVICE_EXCEPTION;
    private final static QName FORMATSERVICESERVICE_QNAME = new QName("http://format/", "FormatServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/users/alumnos-16-17/a0363813/Documentos/distribuidos/format/FormatService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMATSERVICESERVICE_WSDL_LOCATION = url;
        FORMATSERVICESERVICE_EXCEPTION = e;
    }

    public FormatServiceService() {
        super(__getWsdlLocation(), FORMATSERVICESERVICE_QNAME);
    }

    public FormatServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMATSERVICESERVICE_QNAME, features);
    }

    public FormatServiceService(URL wsdlLocation) {
        super(wsdlLocation, FORMATSERVICESERVICE_QNAME);
    }

    public FormatServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMATSERVICESERVICE_QNAME, features);
    }

    public FormatServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FormatServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormatService
     */
    @WebEndpoint(name = "FormatServicePort")
    public FormatService getFormatServicePort() {
        return super.getPort(new QName("http://format/", "FormatServicePort"), FormatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormatService
     */
    @WebEndpoint(name = "FormatServicePort")
    public FormatService getFormatServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://format/", "FormatServicePort"), FormatService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMATSERVICESERVICE_EXCEPTION!= null) {
            throw FORMATSERVICESERVICE_EXCEPTION;
        }
        return FORMATSERVICESERVICE_WSDL_LOCATION;
    }

}
