/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "topic_server.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, init, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
store_topic_text_1(char *topic_name, char *topic_text, int *clnt_res,  CLIENT *clnt)
{
	store_topic_text_1_argument arg;
	arg.topic_name = topic_name;
	arg.topic_text = topic_text;
	return (clnt_call (clnt, store_topic_text, (xdrproc_t) xdr_store_topic_text_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
retrieve_topic_text_1(char *topic_name, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, retrieve_topic_text,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &topic_name,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
