/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "topic_server.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_init_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (init_1_svc(result, rqstp));
}

int
_store_topic_text_1 (store_topic_text_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (store_topic_text_1_svc(argp->topic_name, argp->topic_text, result, rqstp));
}

int
_retrieve_topic_text_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (retrieve_topic_text_1_svc(*argp, result, rqstp));
}

static void
topic_server_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		store_topic_text_1_argument store_topic_text_1_arg;
		char *retrieve_topic_text_1_arg;
	} argument;
	union {
		int init_1_res;
		int store_topic_text_1_res;
		char *retrieve_topic_text_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_init_1;
		break;

	case store_topic_text:
		_xdr_argument = (xdrproc_t) xdr_store_topic_text_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_store_topic_text_1;
		break;

	case retrieve_topic_text:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_retrieve_topic_text_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!topic_server_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (topic_server, topic_server_v1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, topic_server, topic_server_v1, topic_server_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (topic_server, topic_server_v1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, topic_server, topic_server_v1, topic_server_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (topic_server, topic_server_v1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
