/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "topic_server.h"

bool_t
xdr_store_topic_text_1_argument (XDR *xdrs, store_topic_text_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->topic_name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->topic_text, ~0))
		 return FALSE;
	return TRUE;
}
