/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TOPIC_SERVER_H_RPCGEN
#define _TOPIC_SERVER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct store_topic_text_1_argument {
	char *topic_name;
	char *topic_text;
};
typedef struct store_topic_text_1_argument store_topic_text_1_argument;

#define topic_server 99
#define topic_server_v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define init 1
extern  enum clnt_stat init_1(int *, CLIENT *);
extern  bool_t init_1_svc(int *, struct svc_req *);
#define store_topic_text 2
extern  enum clnt_stat store_topic_text_1(char *, char *, int *, CLIENT *);
extern  bool_t store_topic_text_1_svc(char *, char *, int *, struct svc_req *);
#define retrieve_topic_text 3
extern  enum clnt_stat retrieve_topic_text_1(char *, char **, CLIENT *);
extern  bool_t retrieve_topic_text_1_svc(char *, char **, struct svc_req *);
extern int topic_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init 1
extern  enum clnt_stat init_1();
extern  bool_t init_1_svc();
#define store_topic_text 2
extern  enum clnt_stat store_topic_text_1();
extern  bool_t store_topic_text_1_svc();
#define retrieve_topic_text 3
extern  enum clnt_stat retrieve_topic_text_1();
extern  bool_t retrieve_topic_text_1_svc();
extern int topic_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_store_topic_text_1_argument (XDR *, store_topic_text_1_argument*);

#else /* K&R C */
extern bool_t xdr_store_topic_text_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TOPIC_SERVER_H_RPCGEN */
