/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "topic_server.h"


void
topic_server_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	char *store_topic_text_1_topic_name;
	char *store_topic_text_1_topic_text;
	enum clnt_stat retval_3;
	char *result_3;
	char *retrieve_topic_text_1_topic_name;

#ifndef	DEBUG
	clnt = clnt_create (host, topic_server, topic_server_v1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = store_topic_text_1(store_topic_text_1_topic_name, store_topic_text_1_topic_text, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = retrieve_topic_text_1(retrieve_topic_text_1_topic_name, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	topic_server_1 (host);
exit (0);
}
